name: Flutter Android Build

on:
  push:
    branches: [main] # Adjust this to match your main branch name (e.g., master, main, develop)
    tags:
      - "v*" # This will trigger the workflow when you push a tag starting with 'v'

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Get version from pubspec
        id: get_version
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d "'" | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/heads/main')
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
